version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0

  - package-ecosystem: "pip"
    directory: "/python"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0

  - package-ecosystem: "pip"
    directory: "/python/dockerized_labs/broken_auth_lab"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0

  - package-ecosystem: "pip"
    directory: "/python/dockerized_labs/insec_des_lab"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0

  - package-ecosystem: "pip"
    directory: "/python/dockerized_labs/sensitive_data_exposure"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0

  - package-ecosystem: "npm"
    directory: "/reactjs/CVE-2025-55182"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0

  - package-ecosystem: "composer"
    directory: "/php/VulnerableApp-php/vulnerabilities/api"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0
