# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# hadoint is a Dockerfile linter written in Haskell
# that helps you build best practice Docker images.
# More details at https://github.com/hadolint/hadolint
# testing the pipeline

name: Hadolint
# trigger: manual touch to run workflow

on:
  push:
    branches: [ main ]
    paths:
      - "python/**"
      - ".github/workflows/python-hadolint.yml"
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]
    paths:
      - "python/**"
      - ".github/workflows/python-hadolint.yml"


permissions:
  contents: read

jobs:
  hadolint:
    if: github.actor != 'dependabot[bot]'
    name: Run hadolint scanning
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Detect Dockerfile path
        id: dockerfile
        shell: bash
        run: |
          if [ -f "python/Dockerfile" ]; then
            echo "path=python/Dockerfile" >> "$GITHUB_OUTPUT"
          else
            echo "No python/Dockerfile found"
            exit 1
          fi

      - name: Run hadolint
        uses: hadolint/hadolint-action@f988afea3da57ee48710a9795b6bb677cc901183
        with:
          dockerfile: ${{ steps.dockerfile.outputs.path }}

